from functools import lru_cache
from pathlib import Path


from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings

from app.core import config

BACKEND_DIR = Path(__file__).resolve().parents[2]
PDF_PATH = BACKEND_DIR / "ecommerce_rules_and_policies.pdf"
INDEX_PATH = BACKEND_DIR / "faiss_index"

@lru_cache
def get_embeddings() -> OpenAIEmbeddings:
    if not all(
        (
            config.EMBEDDING_API_KEY,
            config.EMBEDDING_BASE_URL,
            config.EMBEDDING_MODEL,
        )
    ):
        raise ValueError("Set the EMBEDDING_* values in the root .env")

    return OpenAIEmbeddings(
        model=config.EMBEDDING_MODEL,
        api_key=config.EMBEDDING_API_KEY,
        base_url=config.EMBEDDING_BASE_URL,
        check_embedding_ctx_length=False,
        request_timeout=30,
        max_retries=1,
    )


@lru_cache
def get_vector_store() -> FAISS:
    if not (
        (INDEX_PATH / "index.faiss").is_file()
        and (INDEX_PATH / "index.pkl").is_file()
    ):
        raise FileNotFoundError(
            "FAISS index is missing. Run python -m app.ai.ingest first."
        )


    return FAISS.load_local(
        folder_path=str(INDEX_PATH),
        embeddings=get_embeddings(),
        # Only load the trusted index generated by your own ingest.py.
        allow_dangerous_deserialization=True,
    )


def retrieve_policies(question: str):
    retriever = get_vector_store().as_retriever(
        search_type="similarity",
        search_kwargs={"k": 4},
    )
    return retriever.invoke(question)